### ISSUE TITLE
Why all my code text color become grey?

### ISSUE THREAD

**Issue by kevinding0218** [hiberbee/jetbrains-ide-theme#49]
After updating the latest hiberbee, most of my code color(declared class, method returned object, etc) becomes grey and hard to differentiate with commented style. Is it just my issue or it's caused by the update?

When I select this plugin I can see my code color changes as expected, however, after intellij did a file index scan, all color becomes grey, I tried to check from Perference->Editor->ColorScheme, but not found where the settings were for those grey out text..

**Comment by CyberRyan1** [comment]
Yeah I am having the same issue as well, seems like it can be because of a new update?

**Comment by CyberRyan1** [comment]
Okay so I found the fix for this in the reviews section of the plugin, you go to Settings > Editor > Color Scheme > Java > Visibility and uncheck the the foreground color under the Visibility section ([review here](https://plugins.jetbrains.com/plugin/12118-hiberbee-theme/reviews#review=57362-57689))

**Comment by kevinding0218** [comment]
@CyberRyan1 Thank you so much! That saved me a thousand!

**Comment by vladyslavvolkov** [comment]
Thanks, guys, I've missed that updated. Patched theme colors, should be available in day or sort of

**Comment by vladyslavvolkov** [comment]
@kevinding0218 Does that issue still make sense?
